### ISSUE TITLE
Private Raids

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#10]
Have an option to create private raids by either new `!private` command or an invite limit of `0` for normal raids.

If a private raid is created these items should be considered:

- no @role mention for raid boss notifications
- not shown on the active raid list
- `!go-live` and PBN should be disabled
- Host can only add invites with `!add`
- No points should be given for the host and invites

**Comment by cjmunoz4** [comment]
Most of this has been implemented, the only thing that's not is not giving out points. Why should these sort of raids not count towards the total?

**Comment by est73** [comment]
I feel a private raid should not have points because the host is not sharing with the community.

If a host only preforms private raids and becomes a “point leader” what incentive would they have to host a public raid?

On Feb 2, 2021, at 7:02 AM, cjmunoz4 <notifications@github.com> wrote:

﻿

Most of this has been implemented, the only thing that's not is not giving out points. Why should these sort of raids not count towards the total?

**Comment by cjmunoz4** [comment]
Oh okay, I get what you mean now. The way these sort of raids are implemented is not different from any other, people can still change the invites-limit and open it up for everyone. It's not strictly private and separate from anything else.
