### ISSUE TITLE
Temporary membership in PRN

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#13]
Add option to toggle temporary membership on/off in PRN.

**Comment by cjmunoz4** [comment]
Sadly, no temporary invites for the raids on the Pokebattler Raid Network means your raids can't be posted on the app. It's how the system works and only a permanent invite and forcing people to stay on the server wouldn't work very well. I'll close this but if you have requests to change the system that the Pokebattler Raid Network uses you can try to contact them directly.
