### ISSUE TITLE
Can’t kick remote invites

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#14]
While hosting a raid I'm not able to kick users from other servers.![image](https://user-images.githubusercontent.com/4969276/105925809-949ee680-5ff5-11eb-8b24-0cd6720eee78.jpeg)![image](https://user-images.githubusercontent.com/4969276/105925821-9c5e8b00-5ff5-11eb-968e-f494f4d652a1.jpeg)

**Comment by cjmunoz4** [comment]
Did the bot sent an output to the first command? That should have worked, as you can kick people based on their discord name

**Comment by est73** [comment]
No, same message for both attempts. It's happened a few times lately.

**Comment by cjmunoz4** [comment]
This issue has been fixed on the newest version of Nexus. :)
