### ISSUE TITLE
Reaction list for !kick

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#15]
Return a reaction list of members for `!kick` command if user to kick is left blank.

Number icons 1-20 can be found on emoji server: https://discord.com/channels/781800122605764628/781800122605764633/781811270667599872

![image](https://user-images.githubusercontent.com/4969276/105926264-8ac9b300-5ff6-11eb-8ed8-17da8fd9eda2.jpeg)

**Comment by est73** [comment]
Obviously this would be a host only command, and would expect the bot to self clean after a reaction is clicked.

Example flow:
- !kick
- Choose users to kick reaction 
- Bot confirms choice 
- Bot removes previous messages related to !kick command
- Bot responds user kicked

**Comment by est73** [comment]
Maybe an alternative to reactions would be to add a number next to user in members list:

![image](https://user-images.githubusercontent.com/4969276/108780643-94730780-751d-11eb-884b-2f1d9e9e6cf4.png)

That way we could use `!kick 1` without having to type out the names.

**Comment by est73** [comment]
This could also be useful for the other commands that require a name input while in the lobby:
> `!strike <trainer> <reason>`
> `!report <trainer>`
> `!punish <trainer>`

**Comment by cjmunoz4** [comment]
I'll close this as it was implemented in the latest version, if there's any further request with it feel free to comment!
