### ISSUE TITLE
Team Roles

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#25]
Nexus will only assign a team role if it's lowercase. Add option to assign role regardless of case being used (Mystic, MYSTIC, MyStIc)

**Comment by cjmunoz4** [comment]
Due to discord limitations (same limitations that doesn't allow members to be recognized if one letter is in a different case), this is not possible as far as I'm aware. If I'm able to find a way I'll implement this but it doesn't seems to be possible :(

**Comment by cjmunoz4** [comment]
Reopening this because there's a way to implement it :)
