### ISSUE TITLE
Raid notifications

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#26]
@ notifications don't come back after raid is re-opened

![image](https://user-images.githubusercontent.com/4969276/107587967-a10b6d80-6bb7-11eb-9c7f-4e63e95abe8d.png)

![image](https://user-images.githubusercontent.com/4969276/107587992-ae285c80-6bb7-11eb-8e3c-28efef5e66aa.png)

![image](https://user-images.githubusercontent.com/4969276/107588027-bbdde200-6bb7-11eb-88aa-c596de6e9546.png)

**Comment by cjmunoz4** [comment]
As discussed, this is by design and not a bug.
