### ISSUE TITLE
New raid creation flow improvement

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#27]
Step 1:
- Add an `X` reaction to cancel the raid.
- Auto delete step after selection is made.

![image](https://user-images.githubusercontent.com/4969276/107607433-1b56e480-6bee-11eb-95fd-f600c6c7c418.png)

Step 2:
- Add an `X` reaction to cancel the raid.
- Add the option to go back a step.
- Auto delete step after selection is made.

![image](https://user-images.githubusercontent.com/4969276/107607541-65d86100-6bee-11eb-9305-b2c5aa1f3781.png)

Step 3a:
- Add the option to go back a step.
- Auto delete step after selection is made.

![image](https://user-images.githubusercontent.com/4969276/107607630-9cae7700-6bee-11eb-9c92-8bdce3b4b529.png)

Step 3b:
- Weather boosted and host only: have the option to go back to `X` on the following click (Currently takes two additional clicks to return back to `X`) 
- Invite limit: change the option to `<<` or `>>` so the host can just add or subtract with an incremental change per click.
- Minimum level has no way to return back to `X`, have the option to go back to `X` on the following click.

![image](https://user-images.githubusercontent.com/4969276/107610239-02eac800-6bf6-11eb-9d03-cc15be724a55.png)

**Comment by cjmunoz4** [comment]
While a lot of this things make sense, some of them are not implemented specifically to lower the amount of interactions and requests the bot does. I'll hold off on most of these until mewtwo comes back, and see if the bot hits the limit of requests or not, depending on that, I'll see if what to do.
