### ISSUE TITLE
Nexus version 0.22.0

### ISSUE THREAD

**Issue by cjmunoz4** [NexusRaidBot/nexus-bot#28]
Added the following commands:

- global-trading-system
- gts accept
- gts failure
- gts offers
- gts pending
- gts remove
- gts search
- gts submit
- gts success

Also updated donation perks:

- Donor role gives you 3 spots on the GTS (simultaneously).
- Supporter role gives you 5 spots on the GTS.
- Contributor role gives you 7 spots on the GTS.
- Benefactor role gives you 10 spots on the GTS.

**Comment by est73** [comment]
Docs updated to add new commands
