### ISSUE TITLE
Pokebattler Raid Network

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#6]
Found some possible bugs testing the PokeBattler app (iOS beta 1.3.10).

1. Raid member count not being updated on the app when !add is used for non-discord users (works with  @users).
2. Raid member count not being updated on the app when !kick or !bye is used
2. No status update on the app when !go is used.
3. Raids are still listed in the app after the raid channel has been closed in Discord.
4. After !kick member can rejoin in app but does not show as being added in the Discord raid channel.
5. Host-only raids are showing 1/5 in app when nobody has joined.

**Comment by cjmunoz4** [comment]
Unsure if 1-5 are on my end or in the Pokebattler app, so I'll send this to them and will let you know what happens, but 6 has been fixed :)

**Comment by est73** [comment]
More problems. :(
7. Was able to join a closed raid via the app but doesn't show on the members list.
8. Nexus give a left message for users not in raid member list.

![image](https://user-images.githubusercontent.com/4969276/103729864-36528b00-4f96-11eb-9ebe-92745fe9bb36.png)

**Comment by cjmunoz4** [comment]
7. If you don't appear on the members list, then you didn't join the raid.
8. Not sure why are able to leave a raid you are not in, but I can check if the user is in the raid before sending that message.

**Comment by cjmunoz4** [comment]
Version 0.13.18 was just pushed that is supposed to have fixed all of these issues. If they persist, feel free to comment in here or make a new issue. Thanks for reporting it :)

**Comment by est73** [comment]
`!add` is being subtracted from the total raid size in the app. The app is showing 1/5 when it should be 2/6. Note the app shows 1/6 prior to `!add` being used.

![image](https://user-images.githubusercontent.com/4969276/104108524-30042d80-527a-11eb-838d-3a7dcb4d8562.png)

![image](https://user-images.githubusercontent.com/4969276/104108461-a9e7e700-5279-11eb-8e98-d0dea4d10d5e.png)

**Comment by cjmunoz4** [comment]
That's a "design decision", trainers that are not from discord are added to the app as "random attackers". Unclear if there's a place you can see this, maybe it's something that's added for the simulations. Also, due to how the raid network works I had to rollback the fix for raids in which the host is only hosting. They are counted and unless pokebattler changes how it works there's nothing that can be done about that.
