### ISSUE TITLE
Raid Train!

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#8]
Add a unlimited timer option on raids to allow for a group to "raid train" without having to worry about the 45 minute limit.

**Comment by est73** [comment]
Or have a `!raid train` option to create a special non-designed Pokémon raid without a timer.

**Comment by est73** [comment]
If a timer must be kept add a "extend timer" reaction on the 5 min warning.

**Comment by cjmunoz4** [comment]
The raid train functionality has been implemented. The raid must have a pokémon asigned (as not many people would jump into a random raid train), and the limit was updated  to 5 hours instead of 1 hour and 45 minutes.
