### ISSUE TITLE
Invite error

### ISSUE THREAD

**Issue by est73** [NexusRaidBot/nexus-bot#9]
Raid went full only showing two joined. !members showing full.

Happened with another user too so the anti spam might be causing the notifications not to show.

![image](https://user-images.githubusercontent.com/4969276/104521244-5cd57f00-55b1-11eb-8e8e-7410142cc0b7.png)

**Comment by est73** [comment]
![image](https://user-images.githubusercontent.com/4969276/104521628-15032780-55b2-11eb-90c2-1463d3e66702.jpeg)

**Comment by cjmunoz4** [comment]
This issue has been resolved. Thanks for reporting it!
